# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.3.6
_src_path: git+https://github.com/OCA/oca-addons-repo-template
ci: Travis
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
rebel_module_groups:
- auth_saml
repo_description: null
repo_name: server-auth
repo_slug: server-auth
travis_apt_packages: []
travis_apt_sources: []
